POST http://localhost:8000/clients
Content-Type: application/json

{
    "nombre": "Manuel",
    "apellidos": "García Jiménez",
    "cedula": 7845123690,
    "edad": 50,
    "sexo": "M",
    "direccion": "Calle 30",
    "telefono": 3245678910
}