PUT http://localhost:8000/clients
Content-Type: application/json
x-client-id: 653f1316bc03409b30063952

{
    "nombre": "Santiago",
    "apellidos": "Barrera Muñoz",
    "cedula": 1020107442,
    "edad": 18,
    "sexo": "M",
    "direccion": "Calle 65",
    "telefono": 3242990764,
    "otro": "nombre"
}

